version: '3.8'

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - jellyfin-config:/config:z
      - /var/lib/media:/data/media:z
    ports:
      - 8096:8096
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - sonarr-config:/config:z
      - /var/lib/media:/data/media:z
      - /mnt/ssd/downloads:/data/downloads:z
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - radarr-config:/config:z
      - /var/lib/media:/data/media:z
      - /mnt/ssd/downloads:/data/downloads:z
    ports:
      - 7878:7878
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - prowlarr-config:/config:z
    ports:
      - 9696:9696
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - qbittorrent-config:/config:z
      - /mnt/ssd/downloads:/data/downloads:z
    ports:
      - "0.0.0.0:8080:8080"
      - "0.0.0.0:6881:6881"
      - "0.0.0.0:6881:6881/udp"
    restart: unless-stopped

volumes:
  jellyfin-config:
    external: true
  sonarr-config:
    external: true
  radarr-config:
    external: true
  prowlarr-config:
    external: true
  qbittorrent-config:
    external: true
